---
name: build epgstation for stg
on:
  push:
    branches: [ "stg" ]
    paths:
      - 'epgstation/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: create epgstation meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/epgstation-ffmpeg-stg
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build epgstation container image
        uses: docker/build-push-action@v5
        with:
          file: ./epgstation/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
